behaviors:
  AvoidAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 3e-4
      beta: 1e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 128
    summary_freq: 10000